export const pokemons = [
  {
    id: 1,
    name: 'Pika',
    stars: 5,
    image: 'pika.png',
    price: 150,
    currency: 'USD',

  },
  {
    id: 2,
    name: 'Bulba',
    stars: 3,
    image: 'bulba.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 3,
    name: 'Squirl',
    stars: 4,
    image: 'squirl.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 4,
    name: 'Psyduck',
    stars: 3,
    image: 'psyduck.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 5,
    name: 'Raichu',
    stars: 4,
    image: 'raichu.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 6,
    name: 'Togepii',
    stars: 3,
    image: 'togepii.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 7,
    name: 'Char',
    stars: 5,
    image: 'char.png',
    price: 150,
    currency: 'USD',
  },
  {
    id: 8,
    name: 'Jiggl',
    stars: 1,
    image: 'jiggl.png',
    price: 150,
    currency: 'USD',
  },
]